spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./survey/survey
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  logging:
    file: logs/myapp.log
    level:
       org.springframework.web: INFO